### ISSUE TITLE
es6 import ?

### ISSUE THREAD

**Issue by daslicht** [anticoders/fake-words#21]
Hi,
how does the import for es6 looks like please?

**Comment by apendua** [comment]
@daslicht I believe this is something like:
```javascript
import { Fake } from 'meteor/anti:meteor-fake';
```
Is it what you're asking about?

**Comment by daslicht** [comment]
yeah its what I am asking.

when I add:
```import { Fake } from 'meteor/anti:meteor-fake';```

I still get: 
```
Cannot find module 'meteor/anti:meteor-fake'
```

**Comment by apendua** [comment]
Ah ... sorry ... I think this should be `anti:fake`. Please double check if it's added to your meteor project.
